const Booking = require("../models/Booking");
const Razorpay = require("razorpay");
const crypto = require("crypto");
const sendEmail = require("../utils/sendEmail");

const razorpay = new Razorpay({
  key_id: process.env.RAZORPAY_KEY_ID,
  key_secret: process.env.RAZORPAY_KEY_SECRET,
});
const createRazorpayOrder = async (req, res) => {
  try {
    const { bookingId } = req.body;

    if (!bookingId) {
      return res.status(400).json({
        success: false,
        message: "Booking ID is required",
      });
    }

    const booking = await Booking.findById(bookingId)
      .populate("user", "name email")
      .populate("event", "title eventDate location");

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking not found",
      });
    }

    if (booking.user._id.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: "You are not allowed to pay for this booking",
      });
    }

    if (booking.bookingStatus === "cancelled") {
      return res.status(400).json({
        success: false,
        message: "Booking has been cancelled",
      });
    }

    if (booking.paymentStatus === "paid") {
      return res.status(400).json({
        success: false,
        message: "Booking is already paid",
      });
    }

    /*
      Razorpay expects INR amount in paise.

      ₹500 -> 50000 paise
    */
    const amountInPaise = Math.round(Number(booking.totalAmount) * 100);

    const order = await razorpay.orders.create({
      amount: amountInPaise,
      currency: "INR",
      receipt: `booking_${booking._id}`,
      notes: {
        bookingId: booking._id.toString(),
      },
    });

    /*
      Store the order ID generated by OUR server.

      We'll use this stored value later when
      verifying the Razorpay signature.
    */
    booking.razorpayOrderId = order.id;

    await booking.save();

    return res.status(200).json({
      success: true,

      order: {
        id: order.id,
        amount: order.amount,
        currency: order.currency,
      },

      keyId: process.env.RAZORPAY_KEY_ID,

      booking: {
        _id: booking._id,
        totalAmount: booking.totalAmount,

        user: {
          name: booking.user.name,
          email: booking.user.email,
        },

        event: {
          title: booking.event?.title,
        },
      },
    });
  } catch (error) {
    console.error("Create Razorpay order error:", error);

    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
const verifyRazorpayPayment = async (req, res) => {
  try {
    const {
      bookingId,
      razorpay_payment_id,
      razorpay_order_id,
      razorpay_signature,
    } = req.body;

    if (
      !bookingId ||
      !razorpay_payment_id ||
      !razorpay_order_id ||
      !razorpay_signature
    ) {
      return res.status(400).json({
        success: false,
        message: "Payment verification details are required",
      });
    }

    const booking = await Booking.findById(bookingId)
      .populate("user", "name email")
      .populate("event", "title eventDate location");

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking not found",
      });
    }

    if (booking.user._id.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: "You are not allowed to verify this payment",
      });
    }

    if (booking.paymentStatus === "paid") {
      return res.status(200).json({
        success: true,
        message: "Payment already verified",
        booking,
      });
    }

    /*
      SECURITY:

      Do not trust the order ID supplied
      by the browser.

      Verify against the order ID stored
      in MongoDB when our server created
      the Razorpay order.
    */

    if (
      !booking.razorpayOrderId ||
      booking.razorpayOrderId !== razorpay_order_id
    ) {
      return res.status(400).json({
        success: false,
        message: "Invalid payment order",
      });
    }

    const body = booking.razorpayOrderId + "|" + razorpay_payment_id;

    const expectedSignature = crypto
      .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
      .update(body)
      .digest("hex");

    /*
      Timing-safe comparison.
    */

    const expectedBuffer = Buffer.from(expectedSignature, "utf8");

    const receivedBuffer = Buffer.from(razorpay_signature, "utf8");

    const signatureValid =
      expectedBuffer.length === receivedBuffer.length &&
      crypto.timingSafeEqual(expectedBuffer, receivedBuffer);

    if (!signatureValid) {
      return res.status(400).json({
        success: false,
        message: "Payment verification failed",
      });
    }

    /*
      Signature is valid.
      NOW we confirm the booking.
    */

    booking.paymentStatus = "paid";
    booking.bookingStatus = "confirmed";

    booking.paymentId = razorpay_payment_id;

    booking.razorpayPaymentId = razorpay_payment_id;

    booking.razorpaySignature = razorpay_signature;

    await booking.save();

    /*
      Purchase confirmation email.

      Email failure should not reverse an
      already successful payment.
    */

    try {
      await sendEmail({
        to: booking.user.email,

        subject: `Booking confirmed: ${booking.event?.title}`,

        html: `
          <h2>Booking Confirmed</h2>

          <p>
            Hi ${booking.user.name},
          </p>

          <p>
            Your payment was successful and your booking has been confirmed.
          </p>

          <h3>
            ${booking.event?.title || "Event"}
          </h3>

          <p>
            Ticket Type:
            ${booking.ticketType}
          </p>

          <p>
            Quantity:
            ${booking.quantity}
          </p>

          <p>
            Amount Paid:
            ₹${booking.totalAmount}
          </p>

          <p>
            Ticket Code:
            <strong>${booking.ticketCode}</strong>
          </p>

          ${
            booking.event?.eventDate
              ? `
                <p>
                  Event Date:
                  ${new Date(booking.event.eventDate).toLocaleDateString()}
                </p>
              `
              : ""
          }

          ${
            booking.event?.location
              ? `
                <p>
                  Location:
                  ${booking.event.location}
                </p>
              `
              : ""
          }

          <p>
            You can view and download your ticket from your bookings.
          </p>
        `,
      });
    } catch (emailError) {
      console.error("Confirmation email failed:", emailError.message);
    }

    return res.status(200).json({
      success: true,
      message: "Payment verified successfully",
      booking,
    });
  } catch (error) {
    console.error("Verify Razorpay payment error:", error);

    return res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};
const processPayment = async (req, res) => {
  try {
    const { bookingId, paymentSuccess } = req.body;

    if (!bookingId) {
      return res.status(400).json({
        success: false,
        message: "Booking ID is required",
      });
    }

    const booking = await Booking.findById(bookingId);

    if (!booking) {
      return res.status(404).json({
        success: false,
        message: "Booking not found",
      });
    }

    if (booking.user.toString() !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: "You are not allowed to pay for this booking",
      });
    }

    if (booking.bookingStatus === "cancelled") {
      return res.status(400).json({
        success: false,
        message: "Booking has been cancelled",
      });
    }

    if (booking.paymentStatus === "paid") {
      return res.status(400).json({
        success: false,
        message: "Booking is already paid",
      });
    }
    if (!paymentSuccess) {
      const event = await Event.findById(booking.event);

      if (event) {
        const ticket = event.ticketTypes.find(
          (ticket) => ticket.name === booking.ticketType,
        );

        if (ticket) {
          ticket.availableQuantity += booking.quantity;
          await event.save();
        }
      }

      booking.paymentStatus = "failed";
      booking.bookingStatus = "cancelled";
    }
    if (paymentSuccess) {
      booking.paymentStatus = "paid";
      booking.bookingStatus = "confirmed";
      booking.paymentId = `PAY-${Date.now()}`;
    } else {
      booking.paymentStatus = "failed";
      booking.bookingStatus = "cancelled";
    }

    await booking.save();

    res.status(200).json({
      success: true,
      message: paymentSuccess ? "Payment successful" : "Payment failed",
      booking,
    });
  } catch (error) {
    res.status(500).json({
      success: false,
      message: error.message,
    });
  }
};

module.exports = {
  processPayment,
  createRazorpayOrder,
  verifyRazorpayPayment,
};
